"""A3 — offline twin of the routing discriminator (design doc §5.1).

Labels each assembled turn the way the live discriminator would label its
initiating request:

    subagent            turn lives in a subagent transcript (or isSidechain)
    utility:compaction  compact-summary turns (quality-critical housekeeping)
    utility             meta/command/housekeeping turns
    user_turn           genuine human instruction (also the ambiguity fallback)

Continuation requests are not separate turns here — they are the
`n_continuations` requests *inside* a turn. Request-level traffic shares are
derived as: continuations / (turns + continuations) per category.

Design rule honored: when unsure, label user_turn (the safe mistake).
"""

from __future__ import annotations

from .turns import Turn

# Harness-generated utility fingerprints seen in instruction text.
_UTILITY_TEXT_MARKERS = (
    "<command-name>",
    "<local-command-caveat>",
    "<system-reminder>",
    "<task-notification>",
    "Caveat: The messages below were generated by the user while running local commands",
)

# origin.kind values that mark harness-generated (non-human) prompts.
_UTILITY_ORIGIN_KINDS = {"task-notification"}


def label_turn(turn: Turn) -> str:
    if turn.source_kind == "subagent" or turn.is_sidechain:
        return "subagent"
    if turn.is_compact_summary:
        return "utility:compaction"
    if turn.is_meta:
        return "utility"
    if turn.origin_kind in _UTILITY_ORIGIN_KINDS:
        return "utility"
    text = turn.instruction_text
    if turn.is_command or any(m in text for m in _UTILITY_TEXT_MARKERS):
        return "utility"
    if not text.strip():
        # No human text at all (attachment-only / synthetic bookkeeping)
        return "utility"
    return "user_turn"


def turn_flags(turn: Turn) -> dict[str, bool]:
    """Signals the escalation controller (§5.5) would have consumed."""
    return {
        "interrupted": turn.interrupted,
        "tool_rejected": turn.tool_rejected,
        "had_errors": turn.n_error_results > 0,
        "edit_failed": turn.n_edit_failures > 0,
        "edit_tripwire": turn.n_edit_failures >= 2,  # the 2-strike threshold
        "parallel_tool_use": turn.parallel_tool_use_msgs > 0,
        "has_thinking": turn.has_thinking,
        "synthetic_model": any(m == "<synthetic>" for m in turn.models),
    }
